---
- name: Create docker unit dir
  file:
    path: "{{ docker['unit']['dir'] }}"
    state: directory

- name: Override docker unit
  template:
    src: templates/docker-override.conf.j2
    dest:  "{{ docker['unit']['dir'] }}/docker-override.conf"
    owner: root
    group: root
    mode: 0644
