---
- name: Confirm Service Exists
  stat: 
    path: /usr/lib/systemd/system/docker.service
  register: service_wrapper

- name: Stop Docker
  service:
    name:  "{{ docker['service'] }}"
    state: stopped
  when:
    - service_wrapper.stat.exists
  register: service_stopped

- include: configure.yml
- include: service.yml
